# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 12f8838aa73427205afafbbdc8ade700f1b62325647d3a664bda238b841f7afaae5d74307941755cd78def93cfa0fdf1aa0c7a542d0c31cc9214a23457786547

test:
  secret_key_base: c54ff286b80787bcced453e69ad4776c8c9fd67362a84d8b902dded548e416e4f80b40b18dbc06e1c8fa79a66682d65113efcc5e29b5fcb92c97008168ed0eea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
